name: PR
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  swiftlint:
    name: "strucc: tests"
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Swiftlint
        run:  brew install swiftlint
      - name: Swiftlint
        run: 'swiftlint --strict'
      - name: Run tests
        run: fastlane tests
